# CONFIG: Replace this with your own application name
application: danfortheast
version: 1
runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: "2.6"
- name: pycrypto
  version: "2.6"
- name: ssl
  version: latest

handlers:
- url: /robots\.txt
  static_files: static/robots.txt
  upload: static/robots\.txt
- url: /favicon\.ico
  static_files: static/favicon.ico
  upload: static/favicon\.ico
  secure: always
- url: /apple-touch-icon-precomposed\.png
  static_files: static/apple-touch-icon-precomposed.png
  upload: static/apple-touch-icon-precomposed\.png
  secure: always
- url: /css
  static_dir: static/css
  secure: always
- url: /js
  static_dir: static/js
  secure: always
- url: /vendor
  static_dir: static/vendor
  secure: always
- url: /files
  static_dir: static/files
  secure: always

# Admin interface, like the one available via the SDK
- url: /admin/.*
  script: google.appengine.ext.admin.application
  login: admin
  secure: always

# Daily log emailer
- url: /_ereporter.*
  script: google.appengine.ext.ereporter.report_generator.application
  login: admin

# Stuff like cron jobs and email taskqueues
- url: /tasks/.*
  script: tasks.app
  login: admin
  secure: always

# The self-serve member join form and PayPal processing
- url: /self-serve/process-member-worker
  script: self-serve.app
  login: admin
  secure: always
- url: /self-serve/expire-member-candidates
  script: self-serve.app
  login: admin
  secure: always
- url: /self-serve/.*
  script: self-serve.app
  secure: always

# Everything else -- direct member join and renewal, maps stuff
- url: /.*
  script: main.app
  secure: always


skip_files:
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$
- ^static/vendor/bootstrap/bootstrap-source.*$
