runtime: python312

# This is higher than default (F1), but the default is slow and memory-constrained
instance_class: F4

automatic_scaling:
  max_instances: 2

handlers:
- url: /robots\.txt
  static_files: static/robots.txt
  upload: static/robots\.txt
- url: /favicon\.ico
  static_files: static/favicon.ico
  upload: static/favicon\.ico
  secure: always
- url: /apple-touch-icon-precomposed\.png
  static_files: static/apple-touch-icon-precomposed.png
  upload: static/apple-touch-icon-precomposed\.png
  secure: always
- url: /css
  static_dir: static/css
  secure: always
- url: /js
  static_dir: static/js
  secure: always
- url: /vendor
  static_dir: static/vendor
  secure: always
- url: /files
  static_dir: static/files
  secure: always

- url: /.*
  script: auto
  secure: always
